### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by zhe13** [winkidney/NetEaseMusicController#5]
=-=为什么要做手机客户端，我觉得不如把web页面设计的好看一点。。。。

**Comment by xuzhenyang** [comment]
同感~

**Comment by winkidney** [comment]
因为手机客户端比较方便吧hhhhh，网页还要打开浏览器，感觉怪怪的……

**Comment by winkidney** [comment]
@zhe13 欢迎修改网页样式的PR：）

**Comment by zhe13** [comment]
好的...如果不嫌弃我今晚就弄.前几天心里有些乱糟糟的....没看notification

**Comment by winkidney** [comment]
@zhe13 赞~

**Comment by winkidney** [comment]
No further comments, closed.
